name: app_crash_logs_to_teams
version: 1.0.2
description: A Dart package to send app crash logs and error details to Microsoft Teams for monitoring.
homepage: https://github.com/keyur005/app_crash_logs_to_teams


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.6.0
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

